Repository syvita/standards, pull requests merged in 2021-05, with the labels that each got.

#8 L3S-04 - Markdown standards
  L3S-04.md
Labels: alpha, documentation, qol

#10 Update README.md
  README.md
Labels: amendment, documentation

#11 Change naming scheme
  README.md
  Syv-01.md
  Syv-02.md
  Syv-02/c4model-1st level-2.png
  Syv-02/c4model-1st level-example.png
  Syv-02/c4model-1st level.png
  Syv-02/c4model-2nd level-example.png
  Syv-02/c4model-2nd level.png
  Syv-02/c4model-3rd level-example.png
  Syv-02/c4model-3rd level.png
  Syv-02/c4model-4th level-example.png
  Syv-03.md
  Syv-04.md
Labels: amendment, documentation, help wanted
